export type GalleryCategory = "events" | "media" | "milestones" | "journey";

export type GalleryItem = {
  id: string;
  src: string;
  width: number;
  height: number;
  category: GalleryCategory;
  titleBn: string;
  titleEn: string;
  altBn: string;
  altEn: string;
};

export const galleryItems: GalleryItem[] = [
  {
    id: "conference-speaker-announcement",
    src: "/gallery/conference-speaker-announcement.webp",
    width: 1280,
    height: 1600,
    category: "events",
    titleBn: "আন্তর্জাতিক সম্মেলনে বক্তা",
    titleEn: "International conference speaker",
    altBn: "২০২৬ সালের সিআইএলটি সম্মেলনের বক্তা ঘোষণায় ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen featured in a 2026 CILT conference speaker announcement",
  },
  {
    id: "voices-of-uae",
    src: "/gallery/voices-of-uae.webp",
    width: 1080,
    height: 1350,
    category: "media",
    titleBn: "ভয়েসেস অব ইউএই",
    titleEn: "Voices of UAE",
    altBn: "ভয়েসেস অব ইউএই ফিচারে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen featured in Voices of UAE",
  },
  {
    id: "editor-biography",
    src: "/gallery/editor-biography.webp",
    width: 1080,
    height: 1131,
    category: "media",
    titleBn: "সম্পাদক পরিচিতি",
    titleEn: "Editor biography",
    altBn: "একটি প্রকাশনায় ড. ফেরদৌস সালেহীনের সম্পাদক পরিচিতির পৃষ্ঠা",
    altEn: "Published editor biography page featuring Dr. Ferdoush Saleheen",
  },
  {
    id: "sura-al-fatiha-sold-out",
    src: "/gallery/sura-al-fatiha-sold-out.webp",
    width: 1254,
    height: 1254,
    category: "milestones",
    titleBn: "সুরা আল-ফাতিহা — পাঠকের ভালোবাসায়",
    titleEn: "Sura Al-Fatiha — a reader milestone",
    altBn: "নিজের সুরা আল-ফাতিহা বই হাতে ড. ফেরদৌস সালেহীন এবং সোল্ড আউট বার্তা",
    altEn: "Dr. Ferdoush Saleheen holding his Sura Al-Fatiha book with a sold-out announcement",
  },
  {
    id: "britishpedia-feature",
    src: "/gallery/britishpedia-feature.webp",
    width: 1080,
    height: 1350,
    category: "milestones",
    titleBn: "ব্রিটিশপিডিয়ায় স্বীকৃতি",
    titleEn: "Featured in Britishpedia",
    altBn: "ব্রিটিশপিডিয়ার সাকসেসফুল পিপল ইন মালয়েশিয়া অ্যান্ড সিঙ্গাপুর বইয়ে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen featured in Britishpedia's Successful People in Malaysia and Singapore",
  },
  {
    id: "conference-panelist",
    src: "/gallery/conference-panelist.webp",
    width: 1280,
    height: 1600,
    category: "events",
    titleBn: "সাসটেইনেবল ট্রান্সপোর্ট সম্মেলন",
    titleEn: "Sustainable transport conference",
    altBn: "সিআইএলটি ২০২৬ সম্মেলনের ইউএই প্যানেলিস্ট হিসেবে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen announced as a UAE panelist for the CILT 2026 conference",
  },
  {
    id: "facebook-four-lakh-views",
    src: "/gallery/facebook-four-lakh-views.webp",
    width: 1254,
    height: 1254,
    category: "milestones",
    titleBn: "চার লাখ দর্শকের মাইলফলক",
    titleEn: "A 400,000-view milestone",
    altBn: "একটি আলোচনার চার লাখ ফেসবুক ভিউ উদযাপনের পোস্টার",
    altEn: "Poster celebrating 400,000 Facebook views for a conversation featuring Dr. Ferdoush Saleheen",
  },
  {
    id: "mountain-and-sea-view",
    src: "/gallery/mountain-and-sea-view.webp",
    width: 1053,
    height: 808,
    category: "journey",
    titleBn: "সমুদ্র ও পাহাড়ের পথে",
    titleEn: "A journey by sea and mountains",
    altBn: "পাহাড়ের ওপর থেকে সমুদ্রবন্দর দৃশ্যের সামনে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen overlooking a seaport from a mountain viewpoint",
  },
  {
    id: "professional-gathering",
    src: "/gallery/professional-gathering.webp",
    width: 1294,
    height: 953,
    category: "events",
    titleBn: "আন্তর্জাতিক সহকর্মীদের সঙ্গে",
    titleEn: "With international colleagues",
    altBn: "একটি পেশাগত আয়োজনে আন্তর্জাতিক সহকর্মীদের সঙ্গে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen with international colleagues at a professional gathering",
  },
  {
    id: "maritime-panel-discussion-wide",
    src: "/gallery/maritime-panel-discussion-wide.webp",
    width: 1080,
    height: 612,
    category: "events",
    titleBn: "মেরিটাইম প্যানেল আলোচনা",
    titleEn: "Maritime panel discussion",
    altBn: "কলেজ অব মেরিটাইম ট্রান্সপোর্ট অ্যান্ড টেকনোলজির প্যানেল আলোচনায় ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen at a College of Maritime Transport and Technology panel discussion",
  },
  {
    id: "maritime-panel-speaking",
    src: "/gallery/maritime-panel-speaking.webp",
    width: 1080,
    height: 611,
    category: "events",
    titleBn: "প্যানেলে বক্তব্য",
    titleEn: "Speaking on a maritime panel",
    altBn: "একটি মেরিটাইম প্যানেল আলোচনায় মাইক্রোফোন হাতে বক্তব্য দিচ্ছেন ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen speaking with a microphone during a maritime panel",
  },
  {
    id: "maritime-resilience-panel",
    src: "/gallery/maritime-resilience-panel.webp",
    width: 941,
    height: 1672,
    category: "events",
    titleBn: "মেরিটাইম রেজিলিয়েন্স প্যানেল",
    titleEn: "Maritime resilience panel",
    altBn: "মেরিটাইম রেজিলিয়েন্স ইন টাইমস অব ক্রাইসিস প্যানেলের পোস্টার",
    altEn: "Poster for the Maritime Resilience in Times of Crisis panel featuring Dr. Ferdoush Saleheen",
  },
  {
    id: "conference-colleague",
    src: "/gallery/conference-colleague.webp",
    width: 1207,
    height: 1200,
    category: "events",
    titleBn: "সম্মেলনের স্মৃতি",
    titleEn: "A conference moment",
    altBn: "একটি সম্মেলনে সহকর্মীর সঙ্গে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen with a colleague at a conference",
  },
  {
    id: "sunway-university",
    src: "/gallery/sunway-university.webp",
    width: 1536,
    height: 2048,
    category: "journey",
    titleBn: "সানওয়ে ইউনিভার্সিটি",
    titleEn: "At Sunway University",
    altBn: "সানওয়ে ইউনিভার্সিটি সাইনেজের সামনে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen standing in front of Sunway University signage",
  },
  {
    id: "global-supply-chain-crisis",
    src: "/gallery/global-supply-chain-crisis.webp",
    width: 1051,
    height: 1345,
    category: "media",
    titleBn: "গ্লোবাল সাপ্লাই চেইন ক্রাইসিস",
    titleEn: "Global supply chain crisis",
    altBn: "মধ্যপ্রাচ্যের নেতৃত্ব ও বৈশ্বিক সাপ্লাই চেইন সংকট বিষয়ে ফিচার পোস্টার",
    altEn: "Feature poster about Middle East leadership and the global supply chain crisis",
  },
  {
    id: "podcast-ceo-conversation",
    src: "/gallery/podcast-ceo-conversation.webp",
    width: 606,
    height: 341,
    category: "media",
    titleBn: "নেতৃত্ব নিয়ে পডকাস্ট আলাপ",
    titleEn: "A podcast conversation on leadership",
    altBn: "নেতৃত্ব ও সিইও বিষয়ক পডকাস্ট আলোচনায় ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen in a podcast conversation about leadership and CEOs",
  },
  {
    id: "diaspora-roundtable",
    src: "/gallery/diaspora-roundtable.webp",
    width: 1023,
    height: 829,
    category: "events",
    titleBn: "ডায়াসপোরা রাউন্ডটেবিল",
    titleEn: "Diaspora roundtable",
    altBn: "ডায়াসপোরা সম্ভাবনা বিষয়ক রাউন্ডটেবিলে অনলাইনে যুক্ত ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen joining a diaspora potential roundtable remotely",
  },
  {
    id: "gulf-news-contents",
    src: "/gallery/gulf-news-contents.webp",
    width: 1005,
    height: 1330,
    category: "media",
    titleBn: "গালফ নিউজে প্রকাশনা",
    titleEn: "Published in Gulf News",
    altBn: "গালফ নিউজের টপ সিইওস অ্যান্ড বিজনেস লিডার্স সংখ্যার সূচিপত্রে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen listed in the Gulf News Top CEOs and Business Leaders contents page",
  },
  {
    id: "gulf-news-feature",
    src: "/gallery/gulf-news-feature.webp",
    width: 1080,
    height: 780,
    category: "media",
    titleBn: "ফ্রম অপারেশনস টু দ্য বোর্ডরুম",
    titleEn: "From operations to the boardroom",
    altBn: "গালফ নিউজে ড. ফেরদৌস সালেহীনের ফ্রম অপারেশনস টু দ্য বোর্ডরুম ফিচার",
    altEn: "From Operations to the Boardroom feature on Dr. Ferdoush Saleheen in Gulf News",
  },
  {
    id: "professional-networking",
    src: "/gallery/professional-networking.webp",
    width: 2048,
    height: 1536,
    category: "events",
    titleBn: "পেশাগত নেটওয়ার্কিং",
    titleEn: "Professional networking",
    altBn: "একটি আন্তর্জাতিক আয়োজনে সহকর্মীর সঙ্গে আলাপরত ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen in conversation with a colleague at an international event",
  },
  {
    id: "uae-malaysia-education-event",
    src: "/gallery/uae-malaysia-education-event.webp",
    width: 2048,
    height: 1536,
    category: "events",
    titleBn: "ইউএই–মালয়েশিয়া শিক্ষা সংযোগ",
    titleEn: "UAE–Malaysia education connection",
    altBn: "ইউএই ও মালয়েশিয়ার পতাকার মাঝে একজন শিক্ষা নেতার সঙ্গে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen with an education leader between the UAE and Malaysia flags",
  },
  {
    id: "dxb-news-network-feature",
    src: "/gallery/dxb-news-network-feature.webp",
    width: 1080,
    height: 585,
    category: "media",
    titleBn: "ডিএক্সবি নিউজ নেটওয়ার্ক ফিচার",
    titleEn: "DXB News Network feature",
    altBn: "ডিএক্সবি নিউজ নেটওয়ার্কের একটি ফিচার গ্রাফিকে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen in a DXB News Network feature graphic",
  },
  {
    id: "logistics-gulf-news-feature",
    src: "/gallery/logistics-gulf-news-feature.webp",
    width: 853,
    height: 581,
    category: "media",
    titleBn: "লজিস্টিকস গালফ নিউজে গবেষণা",
    titleEn: "Research in Logistics Gulf News",
    altBn: "সাপ্লাই চেইন ট্রান্সফরমেশন বিষয়ে লজিস্টিকস গালফ নিউজ ফিচারে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen featured in Logistics Gulf News on supply chain transformation",
  },
  {
    id: "maritime-academy-conference",
    src: "/gallery/maritime-academy-conference.webp",
    width: 1086,
    height: 695,
    category: "events",
    titleBn: "শারজাহ মেরিটাইম একাডেমি সম্মেলন",
    titleEn: "Sharjah Maritime Academy conference",
    altBn: "শারজাহ মেরিটাইম একাডেমির সম্মেলনে আন্তর্জাতিক অংশগ্রহণকারীদের সঙ্গে ড. ফেরদৌস সালেহীন",
    altEn: "Dr. Ferdoush Saleheen with international participants at a Sharjah Maritime Academy conference",
  },
];
