export const newsItems = [
  {
    id: "gulf-news-profile",
    source: "Gulf News",
    typeEn: "Profile",
    typeBn: "ফিচার",
    dateEn: "25 February 2026",
    dateBn: "২৫ ফেব্রুয়ারি ২০২৬",
    datePublished: "2026-02-25",
    title: "From Boardrooms to Classrooms: Dr Saleheen's vision for future supply chains",
    image: "/news/gulf-news-dr-saleheen.jpg",
    imageAlt: "Dr. Ferdoush Saleheen in the Gulf News feature",
    summaryEn: "A profile of Dr. Saleheen’s journey from corporate leadership to academia and his view of supply chains as strategic drivers of future growth.",
    summaryBn: "কর্পোরেট নেতৃত্ব থেকে একাডেমিয়ায় ড. সালেহীনের যাত্রা এবং ভবিষ্যৎ প্রবৃদ্ধির কৌশলগত চালিকা শক্তি হিসেবে সাপ্লাই চেইন নিয়ে তাঁর দৃষ্টিভঙ্গির প্রোফাইল।",
    href: "https://gulfnews.com/amp/story/gn-focus%2Ffrom-boardrooms-to-classrooms-dr-saleheens-vision-for-future-supply-chains-1.500454994",
    featured: true,
  },
  {
    id: "bonik-barta-trade-routes",
    source: "Bonik Barta",
    typeEn: "Opinion",
    typeBn: "মতামত",
    dateEn: "1 April 2026",
    dateBn: "১ এপ্রিল ২০২৬",
    datePublished: "2026-04-01",
    title: "Battle for trade routes: How global crises are creating new logistics power",
    image: "/news/bonik-barta-trade-routes.jpg",
    imageAlt: "Dr. Md Mamun Habib and Dr. Ferdoush Saleheen in Bonik Barta",
    summaryEn: "Ferdoush Saleheen and Md Mamun Habib examine how global shocks, contested corridors, and flexible logistics networks are reshaping economic power.",
    summaryBn: "ফেরদৌস সালেহীন ও মো. মামুন হাবিব বিশ্লেষণ করেছেন—বৈশ্বিক সংকট, প্রতিদ্বন্দ্বিতাপূর্ণ বাণিজ্যপথ ও নমনীয় লজিস্টিকস নেটওয়ার্ক কীভাবে অর্থনৈতিক শক্তির মানচিত্র বদলাচ্ছে।",
    href: "https://en.bonikbarta.com/opinion/mK1ixgFUsyU5kgaD",
    featured: false,
  },
  {
    id: "financial-express-rethink-supply-chains",
    source: "The Financial Express",
    typeEn: "Opinion",
    typeBn: "মতামত",
    dateEn: "2 April 2026",
    dateBn: "২ এপ্রিল ২০২৬",
    datePublished: "2026-04-02",
    title: "Bangladesh must rethink its supply chains",
    image: "/news/financial-express-supply-chains.jpg",
    imageAlt: "Lead image for Bangladesh must rethink its supply chains in The Financial Express",
    summaryEn: "A co-authored case for redesigning Bangladesh’s supply chains around resilience, visibility, diversification, and long-term competitiveness.",
    summaryBn: "স্থিতিস্থাপকতা, দৃশ্যমানতা, বহুমুখীকরণ ও দীর্ঘমেয়াদি প্রতিযোগিতা সক্ষমতাকে কেন্দ্র করে বাংলাদেশের সাপ্লাই চেইন নতুনভাবে সাজানোর যৌথ যুক্তি।",
    href: "https://thefinancialexpress.com.bd/views/opinions/bangladesh-must-rethink-its-supply-chains",
    featured: false,
  },
  {
    id: "routledge-book-listing",
    source: "Routledge · CRC Press",
    typeEn: "Publisher listing",
    typeBn: "প্রকাশকের তালিকা",
    dateEn: "1st edition · Copyright 2027",
    dateBn: "প্রথম সংস্করণ · কপিরাইট ২০২৭",
    datePublished: "2027",
    title: "Sustainable Supply Chain Management: Industry-Driven Practices for a Resilient Future",
    image: "/news/routledge-supply-chain-book.jpg",
    imageAlt: "Routledge cover of Sustainable Supply Chain Management",
    summaryEn: "The official publisher page for the 180-page volume edited by Md. Mamun Habib and Ferdoush Saleheen, with description, contents, and edition details.",
    summaryBn: "মো. মামুন হাবিব ও ফেরদৌস সালেহীন সম্পাদিত ১৮০ পৃষ্ঠার গ্রন্থটির অফিসিয়াল প্রকাশক পৃষ্ঠা—বিবরণ, সূচি ও সংস্করণের তথ্যসহ।",
    href: "https://www.routledge.com/Sustainable-Supply-Chain-Management-Industry-Driven-Practices-for-a-Resilient-Future/Habib-Saleheen/p/book/9781041293132",
    featured: false,
  },
] as const;
